language: python
python:
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install opencv-python"
  - "pip install sphinx sphinx_rtd_theme"
script:
# commands to generate docs
  - make html
# commands to run tests
  - cd tests
  - pytest