language: python
python:
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install opencv-python"
  - "easy_install sphinx"
script:
# commands to generate docs
  - sphinx-quickstart
  - 
  
# commands to run tests
  - cd tests
  - pytest
